//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetDimension.NanUI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetDimension.NanUI.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关闭(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string AboutDialog_CloseButton {
            get {
                return ResourceManager.GetString("AboutDialog.CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 NanUI 界面框架 的本地化字符串。
        /// </summary>
        internal static string AboutDialog_Title {
            get {
                return ResourceManager.GetString("AboutDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载 的本地化字符串。
        /// </summary>
        internal static string Browser_Loading {
            get {
                return ResourceManager.GetString("Browser.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 DevTools(&amp;C) 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_CloseDevTools {
            get {
                return ResourceManager.GetString("ContextMenu.CloseDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 DevTools(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_ShowDevTools {
            get {
                return ResourceManager.GetString("ContextMenu.ShowDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 需要继承IHostWindow接口。 的本地化字符串。
        /// </summary>
        internal static string Exception_DoseNotImpementIHostWindow {
            get {
                return ResourceManager.GetString("Exception.DoseNotImpementIHostWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 需要指定返回值。 的本地化字符串。
        /// </summary>
        internal static string Exception_HaveNoRetureValue {
            get {
                return ResourceManager.GetString("Exception.HaveNoRetureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinFormium 承载窗体 的本地化字符串。
        /// </summary>
        internal static string HostWindow_DefaultTitle {
            get {
                return ResourceManager.GetString("HostWindow.DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinFormium 开发者工具箱 的本地化字符串。
        /// </summary>
        internal static string HostWindow_DevToolsTitle {
            get {
                return ResourceManager.GetString("HostWindow.DevToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息提示 的本地化字符串。
        /// </summary>
        internal static string JSDialog_AlertDialog_Title {
            get {
                return ResourceManager.GetString("JSDialog.AlertDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要确认 的本地化字符串。
        /// </summary>
        internal static string JSDialog_ConfirmDialog_Title {
            get {
                return ResourceManager.GetString("JSDialog.ConfirmDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string JSDialog_NoButton {
            get {
                return ResourceManager.GetString("JSDialog.NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的 的本地化字符串。
        /// </summary>
        internal static string JSDialog_OKButton {
            get {
                return ResourceManager.GetString("JSDialog.OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string JSDialog_YesButton {
            get {
                return ResourceManager.GetString("JSDialog.YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A)... 的本地化字符串。
        /// </summary>
        internal static string SystemMenu_About {
            get {
                return ResourceManager.GetString("SystemMenu.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏(&amp;F) 的本地化字符串。
        /// </summary>
        internal static string SystemMenu_FullScreen {
            get {
                return ResourceManager.GetString("SystemMenu.FullScreen", resourceCulture);
            }
        }
    }
}
