//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormium.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormium.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close DevTools 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_CloseDevTools {
            get {
                return ResourceManager.GetString("ContextMenu_CloseDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_Cut {
            get {
                return ResourceManager.GetString("ContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_Paste {
            get {
                return ResourceManager.GetString("ContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_Redo {
            get {
                return ResourceManager.GetString("ContextMenu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectAll 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_SelectAll {
            get {
                return ResourceManager.GetString("ContextMenu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show &amp;DevTools 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_ShowDevTools {
            get {
                return ResourceManager.GetString("ContextMenu_ShowDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string ContextMenu_Undo {
            get {
                return ResourceManager.GetString("ContextMenu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinFormium Developer&apos;s Toolbox 的本地化字符串。
        /// </summary>
        internal static string DevTools_Window_Title {
            get {
                return ResourceManager.GetString("DevTools_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 libcef.dll was not found, or the architecture of libcef.dll is incorrect. 的本地化字符串。
        /// </summary>
        internal static string Exception_LibCefLoadFailed_NotFoundOrArchError {
            get {
                return ResourceManager.GetString("Exception_LibCefLoadFailed_NotFoundOrArchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load 的本地化字符串。
        /// </summary>
        internal static string Exception_LibCefLoadFailed_Title {
            get {
                return ResourceManager.GetString("Exception_LibCefLoadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application does not match the API version of libcef.dll loaded. 的本地化字符串。
        /// </summary>
        internal static string Exception_LibCefLoadFailed_VersionMismatch {
            get {
                return ResourceManager.GetString("Exception_LibCefLoadFailed_VersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The libcef.dll file path could not be found or the cef runtime file structure is incorrect. 的本地化字符串。
        /// </summary>
        internal static string Exception_LibCefNotFound {
            get {
                return ResourceManager.GetString("Exception_LibCefNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown platform architecture. 的本地化字符串。
        /// </summary>
        internal static string Exception_UnkownPlatformArchitecture {
            get {
                return ResourceManager.GetString("Exception_UnkownPlatformArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinFormium has been initialized and only one instance can be run. 的本地化字符串。
        /// </summary>
        internal static string Exception_WinFormiumInitializationFailed {
            get {
                return ResourceManager.GetString("Exception_WinFormiumInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string External_Browser_Loading {
            get {
                return ResourceManager.GetString("External_Browser_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinFormium Browser 的本地化字符串。
        /// </summary>
        internal static string External_Browser_Title {
            get {
                return ResourceManager.GetString("External_Browser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;About ... 的本地化字符串。
        /// </summary>
        internal static string SystemMenu_About {
            get {
                return ResourceManager.GetString("SystemMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;FullScreen 的本地化字符串。
        /// </summary>
        internal static string SystemMenu_FullScreen {
            get {
                return ResourceManager.GetString("SystemMenu_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your applicaiton cannot run without the SubProcess. 的本地化字符串。
        /// </summary>
        internal static string WinFormiumApp_Subprocess_NotFound_Text {
            get {
                return ResourceManager.GetString("WinFormiumApp_Subprocess_NotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string WinFormiumApp_Subprocess_NotFound_Title {
            get {
                return ResourceManager.GetString("WinFormiumApp_Subprocess_NotFound_Title", resourceCulture);
            }
        }
    }
}
