//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormium.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///  P.O.W.E.R.E.D BY
        ///  __       __ __          ________                                __
        /// |  \  _  |  \  \        |        \                              |  \
        /// | ▓▓ / \ | ▓▓\▓▓_______ | ▓▓▓▓▓▓▓▓ ______   ______  ______ ____  \▓▓__    __ ______ ____
        /// | ▓▓/  ▓\| ▓▓  \       \| ▓▓__    /      \ /      \|      \    \|  \  \  |  \      \    \
        /// | ▓▓  ▓▓▓\ ▓▓ ▓▓ ▓▓▓▓▓▓▓\ ▓▓  \  |  ▓▓▓▓▓▓\  ▓▓▓▓▓▓\ ▓▓▓▓▓▓\▓▓▓▓\ ▓▓ ▓▓  | ▓▓ ▓▓▓▓▓▓\▓▓▓▓\
        /// | ▓▓ ▓▓\▓▓\▓▓ ▓▓ ▓▓  | ▓▓ ▓▓▓▓▓  | ▓▓  | ▓▓ ▓▓   \▓▓ ▓▓ | ▓▓ | ▓▓ ▓▓ ▓▓  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ASCII {
            get {
                return ResourceManager.GetString("ASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Chromium {
            get {
                object obj = ResourceManager.GetObject("Chromium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy_16px {
            get {
                object obj = ResourceManager.GetObject("copy_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cut_16px {
            get {
                object obj = ResourceManager.GetObject("cut_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap devtools_16px {
            get {
                object obj = ResourceManager.GetObject("devtools_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DevToolsIcon {
            get {
                object obj = ResourceManager.GetObject("DevToolsIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 var formium;
        ///
        ///(function ($window) {
        ///
        ///    const CMD_ATTR_PREFIX = &quot;formium-command&quot;;
        ///
        ///    let isDocumentReady = false;
        ///    let isContextReady = false;
        ///
        ///    const readyCallbacks = [];
        ///    const contextReadyCallbacks = [];
        ///
        ///    const messageDispatchers = {};
        ///
        ///
        ///    let lastWindowState = null;
        ///
        ///    let globalMouseEventHandlerRegistered = false;
        ///
        ///    const raiseHostWindowEvent = (eventName, eventArgs) =&gt; {
        ///
        ///        if (!isContextReady) return;
        ///
        ///        window.dispatchEvent(new CustomEvent(        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FormiumWindowBindingObject {
            get {
                return ResourceManager.GetString("FormiumWindowBindingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The libcef.dll file path could not be found or the cef runtime file structure is incorrect. 的本地化字符串。
        /// </summary>
        internal static string LibCefNotFoundException {
            get {
                return ResourceManager.GetString("LibCefNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MIT License (MIT)
        ///
        ///Copyright (C) 2014 - {0}, Xuanchen Lin all rights reserved.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the followin [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap paste_16px {
            get {
                object obj = ResourceManager.GetObject("paste_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap redo_16px {
            get {
                object obj = ResourceManager.GetObject("redo_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap undo_16px {
            get {
                object obj = ResourceManager.GetObject("undo_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
