//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "100.0.24+g0783cf8+chromium-100.0.4896.127";
        public const int CEF_VERSION_MAJOR = 100;
        public const int CEF_COMMIT_NUMBER = 2544;
        public const string CEF_COMMIT_HASH = "0783cf8db5b02f28d13383c53911b9a6bc31b034";
        
        public const int CHROME_VERSION_MAJOR = 100;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4896;
        public const int CHROME_VERSION_PATCH = 127;
        
        public const string CEF_API_HASH_UNIVERSAL = "c32d3ae315c5991d1bd81c412635d95a3fd353f8";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "cb1d823e15caa7e7b6074e3e612d111145b374d1";
        public const string CEF_API_HASH_PLATFORM_MACOS = "7e3a768a3b73a514763ce9902afb85775ca8c83d";
        public const string CEF_API_HASH_PLATFORM_LINUX = "bc9260335c9493beb100645dbccd587e62925b9e";
    }
}
