//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormiumClient.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormiumClient.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 找不到示例子进程 的本地化字符串。
        /// </summary>
        internal static string CannotFoundSubprocessCaption {
            get {
                return ResourceManager.GetString("CannotFoundSubprocessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到位于{0}的子进程，是否使用主进程继续运行？ 的本地化字符串。
        /// </summary>
        internal static string CannotFoundSubprocessMessage {
            get {
                return ResourceManager.GetString("CannotFoundSubprocessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要关闭 NanUI 示例程序吗？ 的本地化字符串。
        /// </summary>
        internal static string CloseConfirmDialogMessage {
            get {
                return ResourceManager.GetString("CloseConfirmDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string CloseConfirmDialogTitle {
            get {
                return ResourceManager.GetString("CloseConfirmDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NanUI 示例程序 的本地化字符串。
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 NanUI 示例程序 的本地化字符串。
        /// </summary>
        internal static string StartupWindowTitle {
            get {
                return ResourceManager.GetString("StartupWindowTitle", resourceCulture);
            }
        }
    }
}
