//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "90.6.5+g7a604aa+chromium-90.0.4430.93";
        public const int CEF_VERSION_MAJOR = 90;
        public const int CEF_COMMIT_NUMBER = 2356;
        public const string CEF_COMMIT_HASH = "7a604aacf4bbbef0fc4d64185feb672f12880391";
        
        public const int CHROME_VERSION_MAJOR = 90;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4430;
        public const int CHROME_VERSION_PATCH = 93;
        
        public const string CEF_API_HASH_UNIVERSAL = "d026196d35d8894a836ab3a3d033b84195cdb835";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "4150bd26e7bf639a9b1f3e5860af8c76eeae8570";
        public const string CEF_API_HASH_PLATFORM_MACOS = "5cc32f88bd134410eff86b21095138b339d572f2";
        public const string CEF_API_HASH_PLATFORM_LINUX = "b227b3fdd6142a9d8ff0f2252a71425f15960800";
    }
}
