//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace WinFormium.CefGlue
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using WinFormium.CefGlue.Interop;
    
    // Role: PROXY
    public sealed unsafe partial class CefSharedMemoryRegion : IDisposable
    {
        internal static CefSharedMemoryRegion FromNative(cef_shared_memory_region_t* ptr)
        {
            return new CefSharedMemoryRegion(ptr);
        }
        
        internal static CefSharedMemoryRegion FromNativeOrNull(cef_shared_memory_region_t* ptr)
        {
            if (ptr == null) return null;
            return new CefSharedMemoryRegion(ptr);
        }
        
        private cef_shared_memory_region_t* _self;
        
        private CefSharedMemoryRegion(cef_shared_memory_region_t* ptr)
        {
            if (ptr == null) throw new ArgumentNullException("ptr");
            _self = ptr;
        }
        
        ~CefSharedMemoryRegion()
        {
            if (_self != null)
            {
                Release();
                _self = null;
            }
        }
        
        public void Dispose()
        {
            if (_self != null)
            {
                Release();
                _self = null;
            }
            GC.SuppressFinalize(this);
        }
        
        internal void AddRef()
        {
            cef_shared_memory_region_t.add_ref(_self);
        }
        
        internal bool Release()
        {
            return cef_shared_memory_region_t.release(_self) != 0;
        }
        
        internal bool HasOneRef
        {
            get { return cef_shared_memory_region_t.has_one_ref(_self) != 0; }
        }
        
        internal bool HasAtLeastOneRef
        {
            get { return cef_shared_memory_region_t.has_at_least_one_ref(_self) != 0; }
        }
        
        internal cef_shared_memory_region_t* ToNative()
        {
            AddRef();
            return _self;
        }
    }
}
