//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetDimension.NanUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetDimension.NanUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///  P.O.W.E.R.E.D BY                          
        ///  ███╗   ██╗ █████╗ ███╗   ██╗██╗   ██╗██╗  
        ///  ████╗  ██║██╔══██╗████╗  ██║██║   ██║██║  
        ///  ██╔██╗ ██║███████║██╔██╗ ██║██║   ██║██║  
        ///  ██║╚██╗██║██╔══██║██║╚██╗██║██║   ██║██║  
        ///  ██║ ╚████║██║  ██║██║ ╚████║╚██████╔╝██║  
        ///  ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  
        ///                            S.I.N.C.E 2016  
        ///                                             的本地化字符串。
        /// </summary>
        internal static string ASCII_NanUI_Logo {
            get {
                return ResourceManager.GetString("ASCII_NanUI_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon DevToolsIcon {
            get {
                object obj = ResourceManager.GetObject("DevToolsIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DropShadow {
            get {
                object obj = ResourceManager.GetObject("DropShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap GlowShadow {
            get {
                object obj = ResourceManager.GetObject("GlowShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 var Formium = Formium || {};
        ///
        ///(function ($this) {
        ///
        ///    const CMD_ATTR_PREFIX = &quot;formium-command&quot;;
        ///
        ///    const RAISE_FUNC_NAME = &quot;__formium_raiseHostWindowEvent&quot;;
        ///
        ///    const GLOBAL_CLICK_HANDLER_REGISTERED =
        ///        &quot;__formium_global_click_handler_registered&quot;;
        ///
        ///
        ///    let isV8Ready = false;
        ///
        ///    let isDomReady = false;
        ///
        ///    const readyFunctions = [];
        ///
        ///    const contextReadyFunctions = [];
        ///
        ///    $this._setContextReady =  () =&gt; {
        ///
        ///        isV8Ready = true;
        ///
        ///        if (!window.hasOwnPropert [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HostWindowJavaScriptExtension {
            get {
                return ResourceManager.GetString("HostWindowJavaScriptExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Licenses {
            get {
                object obj = ResourceManager.GetObject("Licenses", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Powered {
            get {
                object obj = ResourceManager.GetObject("Powered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RoundedDropShadow {
            get {
                object obj = ResourceManager.GetObject("RoundedDropShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RoundedGlowShadow {
            get {
                object obj = ResourceManager.GetObject("RoundedGlowShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RoundedShadow {
            get {
                object obj = ResourceManager.GetObject("RoundedShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Shadow {
            get {
                object obj = ResourceManager.GetObject("Shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
