//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "80.1.15+g7b802c9+chromium-80.0.3987.163";
        public const int CEF_VERSION_MAJOR = 80;
        public const int CEF_COMMIT_NUMBER = 2163;
        public const string CEF_COMMIT_HASH = "7b802c9272e5371e7a30d1283e96e18d984eae55";
        
        public const int CHROME_VERSION_MAJOR = 80;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 3987;
        public const int CHROME_VERSION_PATCH = 163;
        
        public const string CEF_API_HASH_UNIVERSAL = "5f9a1d7977affd8006aff83fe4ab7c408c3288f0";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "5131b8a7e8097ab4c415227c65e7385a3363b56f";
        public const string CEF_API_HASH_PLATFORM_MACOSX = "136b3df0013c4997f81de2eba43fca2e36ad603c";
        public const string CEF_API_HASH_PLATFORM_LINUX = "7353c7e128ad2e0185a93f488876e607f57f576a";
    }
}
