//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace WinFormium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "109.1.18+gf1c41e4+chromium-109.0.5414.120";
        public const int CEF_VERSION_MAJOR = 109;
        public const int CEF_COMMIT_NUMBER = 2719;
        public const string CEF_COMMIT_HASH = "f1c41e4b1392ef8816171c4d51a2fca308db5501";
        
        public const int CHROME_VERSION_MAJOR = 109;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 5414;
        public const int CHROME_VERSION_PATCH = 120;
        
        public const string CEF_API_HASH_UNIVERSAL = "80dc2ef26a1ac3a35c798a01adc88240759ac85a";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "c3f39d68cb97e87872a59a42c9255460ef4d7170";
        public const string CEF_API_HASH_PLATFORM_MACOS = "589830b49e03e9f4ae2c050125bcdafacbb248dd";
        public const string CEF_API_HASH_PLATFORM_LINUX = "e3e836b304098732708acf972e82fb6fcb2516a7";
    }
}
